# Generated by Django 5.2.6 on 2025-09-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='visita',
            name='hora_entrada',
            field=models.TimeField(),
        ),
    ]
