# Generated by Django 5.2.6 on 2025-09-26 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_remove_visita_fecha_alter_visita_hora_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
