# Generated by Django 5.2.6 on 2025-09-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_visita_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
